# Generated by Django 6.0 on 2026-08-22 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardTransaction',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('customer_id', models.CharField(max_length=64)),
                ('amount', models.FloatField()),
                ('merchant', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('device_id', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PROCESSED', max_length=32)),
                ('fraud_probability', models.FloatField(default=0.0)),
                ('risk_score', models.IntegerField(default=0)),
                ('risk_level', models.CharField(default='LOW', max_length=16)),
                ('is_fraud_predicted', models.IntegerField(default=0)),
                ('explanation_reasons', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('risk_score', models.IntegerField()),
                ('reasons', models.JSONField()),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.creditcardtransaction')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
